-- Schema version 2; applied once by backend startup.
CREATE TABLE user_roles (user_role_id integer PRIMARY KEY, user_role_name text UNIQUE NOT NULL);
INSERT INTO user_roles VALUES (1, 'admin'), (2, 'user');
CREATE TABLE users (
    user_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_name varchar(48) NOT NULL CHECK (length(trim(user_name)) > 0),
    password_hash text NOT NULL,
    user_role_id integer NOT NULL REFERENCES user_roles,
    is_active boolean NOT NULL DEFAULT true,
    last_activated_at timestamptz NOT NULL DEFAULT now(),
    last_deactivated_at timestamptz
);
CREATE UNIQUE INDEX unique_active_username ON users(user_name) WHERE is_active;
CREATE TABLE contacts (
    contact_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    contact_no varchar(24) NOT NULL,
    user_id uuid NOT NULL REFERENCES users ON DELETE CASCADE
);
CREATE TABLE sessions (
    session_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES users ON DELETE CASCADE,
    expiry_date timestamptz NOT NULL DEFAULT now() + interval '7 days',
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE attachment_types (attachment_type_id integer PRIMARY KEY, attachment_type_name text UNIQUE NOT NULL);
INSERT INTO attachment_types VALUES (1, 'image_attachment'), (2, 'voice_attachment');
CREATE TABLE allowed_extensions (
    extension_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    attachment_type_id integer NOT NULL REFERENCES attachment_types,
    extension_name varchar(10) NOT NULL,
    UNIQUE(attachment_type_id, extension_name), UNIQUE(extension_id, attachment_type_id)
);
INSERT INTO allowed_extensions (attachment_type_id, extension_name)
SELECT 1, unnest(ARRAY['jpg','jpeg','png','webp','gif','heic','heif','avif','bmp']);
INSERT INTO allowed_extensions (attachment_type_id, extension_name)
SELECT 2, unnest(ARRAY['mp3','m4a','wav','ogg','webm','aac','flac','mp4']);
CREATE TABLE attachments (
    attachment_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    attachment_type_id integer NOT NULL,
    extension_id integer NOT NULL,
    attachment_url text NOT NULL,
    original_name text NOT NULL,
    content_type text NOT NULL,
    uploaded_by uuid NOT NULL REFERENCES users,
    is_submitted boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY(extension_id, attachment_type_id) REFERENCES allowed_extensions(extension_id, attachment_type_id)
);
CREATE TABLE category_groups (category_group_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category_group_name varchar(48) UNIQUE NOT NULL, is_active boolean NOT NULL DEFAULT true);
INSERT INTO category_groups(category_group_id,category_group_name) VALUES (1, 'Material'), (2, 'Labour');
SELECT setval(pg_get_serial_sequence('category_groups','category_group_id'), 2);
CREATE TABLE transaction_types (transaction_type_id integer PRIMARY KEY, transaction_type_name varchar(48) UNIQUE NOT NULL);
INSERT INTO transaction_types VALUES (1, 'General');
CREATE TABLE heads (
    head_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    parent_head_id integer REFERENCES heads,
    attachment_id integer REFERENCES attachments,
    head_name varchar(160) NOT NULL CHECK (length(trim(head_name)) > 0),
    head_description text,
    is_active boolean NOT NULL DEFAULT true,
    is_transactionable boolean NOT NULL DEFAULT false,
    is_deleted boolean NOT NULL DEFAULT false,
    CHECK (head_id <> parent_head_id)
);
-- Tombstones keep permission IDs and historical versions unchanged after deletion/merge.
CREATE UNIQUE INDEX unique_live_head_name ON heads(head_name) WHERE NOT is_deleted;
CREATE TABLE user_head_permissions (
    head_id integer NOT NULL REFERENCES heads,
    user_id uuid NOT NULL REFERENCES users ON DELETE CASCADE,
    PRIMARY KEY (head_id, user_id)
);
CREATE TABLE transactions (
    transaction_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    head_id integer NOT NULL REFERENCES heads,
    category_group_id integer NOT NULL REFERENCES category_groups,
    user_id uuid NOT NULL REFERENCES users,
    created_by_user_id uuid NOT NULL REFERENCES users,
    current_version_id integer NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE transaction_versions (
    version_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    transaction_id integer NOT NULL REFERENCES transactions ON DELETE CASCADE,
    transaction_amount numeric(18,2) NOT NULL CHECK (transaction_amount >= 0),
    transaction_type_id integer NOT NULL REFERENCES transaction_types,
    created_at timestamptz NOT NULL DEFAULT now(),
    editor_id uuid NOT NULL REFERENCES users,
    action text NOT NULL,
    head_id integer NOT NULL REFERENCES heads,
    category_group_id integer NOT NULL REFERENCES category_groups,
    is_active boolean NOT NULL,
    head_path text NOT NULL,
    category_name text NOT NULL,
    UNIQUE(transaction_id, version_id)
);
ALTER TABLE transactions ADD CONSTRAINT transactions_current_version
    FOREIGN KEY(transaction_id, current_version_id)
    REFERENCES transaction_versions(transaction_id, version_id) DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE transaction_version_attachments (
    version_id integer NOT NULL REFERENCES transaction_versions ON DELETE CASCADE,
    attachment_id integer NOT NULL REFERENCES attachments,
    PRIMARY KEY(version_id, attachment_id)
);
CREATE TABLE schema_version (version integer PRIMARY KEY);
INSERT INTO schema_version VALUES (2);
CREATE TABLE head_revision (revision integer NOT NULL);
INSERT INTO head_revision VALUES (0);
