import { useEffect, useState } from 'react'
import { api } from '../../api'
import type { Head } from '../../types'
import { Alert, Empty, Icon, Modal, PageTitle, flatten } from '../../ui'
import { ImagePicker } from '../../Attachments'
export default function Heads() {
 const [tree,setTree]=useState<Head[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[loading,setLoading]=useState(true),[open,setOpen]=useState<Set<number>>(new Set()),[editing,setEditing]=useState<Head|null>(null),[creating,setCreating]=useState(false),[moving,setMoving]=useState<Head|null>(null),[target,setTarget]=useState('')
 const [form,setForm]=useState({name:'',description:'',parent:'',transactionable:false,active:true,image:null as number|null})
 async function load(){try{setTree(await api.get<Head[]>('/heads/tree'))}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 function edit(h:Head|null){setError('');setEditing(h);setCreating(!h);setForm({name:h?.head_name||'',description:h?.head_description||'',parent:h?.parent_head_id?.toString()||'',transactionable:h?.is_transactionable||false,active:h?.is_active??true,image:h?.image_id??null})}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const body={head_name:form.name.trim(),head_description:form.description.trim()||null,is_transactionable:form.transactionable,is_active:form.active,image_id:form.image};if(editing)await api.patch(`/heads/${editing.head_id}`,body);else await api.post('/heads',{...body,parent_head_id:Number(form.parent)||null});setCreating(false);setEditing(null);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function move(){if(!moving)return;setBusy(true);setError('');try{await api.post(`/heads/${moving.head_id}/move`,{new_parent_head_id:Number(target)||null});setMoving(null);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function toggle(id:number){setOpen(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}
 function row(h:Head,depth=0):React.ReactNode{return <div key={h.head_id}><div className="head-admin-row" style={{'--depth':Math.min(depth,5)} as React.CSSProperties}><button className="tree-toggle" aria-label={`${open.has(h.head_id)?'Collapse':'Expand'} ${h.head_name}`} disabled={!h.children.length} onClick={()=>toggle(h.head_id)}><span className={open.has(h.head_id)?'rotated':''}><Icon name="arrow" size={16}/></span></button><span className="head-symbol"><Icon name="folder"/></span><div className="head-admin-name"><strong>{h.head_name}</strong><small>{h.children.length} subheads{h.head_description?' · '+h.head_description:''}</small></div><span className={`tag ${h.is_active?'':'muted'}`}>{h.is_active?h.is_transactionable?'Accepts entries':'Navigation':'Inactive'}</span><div className="row"><button className="subtle" onClick={()=>edit(h)}>Edit</button><button className="subtle" onClick={()=>{setError('');setMoving(h);setTarget(h.parent_head_id?.toString()||'')}}>Move</button></div></div>{open.has(h.head_id)&&h.children.map(c=>row(c,depth+1))}</div>}
 const flat=flatten(tree),invalid=moving?new Set(flatten([moving]).map(h=>h.head_id)):new Set<number>()
 return <><PageTitle title="Heads" subtitle="Give every entry a place. Organise your office your way." action={<button onClick={()=>edit(null)}><Icon name="plus" size={18}/>New head</button>}/>{!creating&&!editing&&!moving&&<Alert>{error}</Alert>}<section className="ledger"><div className="section-title"><div><h2>Your head tree <span className="count">{flat.length}</span></h2><p>Any head can accept entries and contain subheads.</p></div><button className="subtle" onClick={()=>setOpen(open.size?new Set():new Set(flat.map(h=>h.head_id)))}>{open.size?'Collapse all':'Expand all'}</button></div>{loading?<div className="spin"/>:tree.length?tree.map(h=>row(h)):<Empty title="Start with a head">Add a top-level head, then organise its subheads.</Empty>}</section>
 {(creating||editing)&&<Modal title={editing?'Edit head':'Create a head'} onClose={()=>{if(!busy&&!uploading){setCreating(false);setEditing(null)}}}><Alert>{error}</Alert><form onSubmit={save}><label htmlFor="head-name">Name</label><input id="head-name" required maxLength={48} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><label htmlFor="description">Description (optional)</label><textarea id="description" maxLength={2000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/>{!editing&&<><label htmlFor="parent">Inside</label><select id="parent" value={form.parent} onChange={e=>setForm({...form,parent:e.target.value})}><option value="">Top level</option>{flat.map(h=><option key={h.head_id} value={h.head_id}>{h.path}</option>)}</select></>}<label className="toggle-row"><span><strong>Accept transactions</strong><small>Show “Make transaction” to permitted users.</small></span><input type="checkbox" checked={form.transactionable} onChange={e=>setForm({...form,transactionable:e.target.checked})}/></label>{editing&&<label className="toggle-row"><span><strong>Active</strong><small>Turning this off blocks entries in the whole branch.</small></span><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/></label>}<details className="optional-section"><summary>Head photo (optional)</summary><ImagePicker value={form.image} onChange={image=>setForm({...form,image})} onBusy={setUploading}/></details><button className="block" disabled={busy||uploading||!form.name.trim()}>{busy?'Saving…':editing?'Save changes':'Create head'}</button></form></Modal>}
 {moving&&<Modal title={`Move ${moving.head_name}`} onClose={()=>{if(!busy)setMoving(null)}}><Alert>{error}</Alert><p>The whole branch moves together. Existing entries keep this head; inherited access follows its new location.</p><label htmlFor="move-parent">New parent</label><select id="move-parent" value={target} onChange={e=>setTarget(e.target.value)}><option value="">Top level</option>{flat.filter(h=>!invalid.has(h.head_id)).map(h=><option key={h.head_id} value={h.head_id}>{h.path}</option>)}</select><button className="block" disabled={busy} onClick={move}>{busy?'Moving…':'Move head'}</button></Modal>}</>
}
