import { useEffect, useState } from 'react'
import { api } from '../../api'
import type { PaymentMedium } from '../../types'
import { Alert, Icon, PageTitle } from '../../ui'
export default function Settings(){
 const [mediums,setMediums]=useState<PaymentMedium[]>([]),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pw,setPw]=useState({current:'',next:'',confirm:''})
 async function load(){setMediums(await api.get<PaymentMedium[]>('/settings/payment-mediums'))}
 useEffect(()=>{load().catch(e=>setError(e.message))},[])
 async function run(fn:()=>Promise<unknown>,message:string,done?:()=>void){setBusy(true);setError('');setNotice('');try{await fn();done?.();await load();setNotice(message)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><PageTitle title="Settings" subtitle="The small details that keep your office running."/><Alert>{error}</Alert><Alert success>{notice}</Alert><div className="detail-grid"><section className="card"><h2>Payment methods</h2><p className="hint">Methods in use are kept to preserve transaction history.</p>{mediums.map(m=><form className="medium-row" key={m.payment_medium_id} onSubmit={e=>{e.preventDefault();void run(()=>api.patch(`/settings/payment-mediums/${m.payment_medium_id}`,{name:m.payment_medium_name.trim()}),'Payment method saved.')}}><div><label htmlFor={`medium-${m.payment_medium_id}`}>Method · {m.reference_count||0} versions</label><input id={`medium-${m.payment_medium_id}`} required maxLength={48} value={m.payment_medium_name} onChange={e=>setMediums(ms=>ms.map(x=>x.payment_medium_id===m.payment_medium_id?{...x,payment_medium_name:e.target.value}:x))}/></div><button className="secondary" disabled={busy||!m.payment_medium_name.trim()}>Save</button><button type="button" className="icon-button danger-text" aria-label={`Delete ${m.payment_medium_name}`} title={m.reference_count?'This method is in use':'Delete method'} disabled={busy||!!m.reference_count} onClick={()=>{if(window.confirm(`Delete ${m.payment_medium_name}?`))void run(()=>api.delete(`/settings/payment-mediums/${m.payment_medium_id}`),'Payment method deleted.')}}><Icon name="close" size={18}/></button></form>)}<form onSubmit={e=>{e.preventDefault();void run(()=>api.post('/settings/payment-mediums',{name:name.trim()}),'Payment method added.',()=>setName(''))}}><label htmlFor="new-medium">New payment method</label><div className="row"><input id="new-medium" required maxLength={48} placeholder="e.g. Easypaisa" value={name} onChange={e=>setName(e.target.value)}/><button disabled={busy||!name.trim()}>Add</button></div></form></section><section className="card"><h2>Your password</h2><p className="hint">Changing it signs out your other sessions.</p><form onSubmit={e=>{e.preventDefault();if(pw.next!==pw.confirm){setError('New passwords do not match.');return}void run(()=>api.post('/auth/change-password',{current_password:pw.current,new_password:pw.next}),'Password changed.',()=>setPw({current:'',next:'',confirm:''}))}}><label htmlFor="current-pass">Current password</label><input id="current-pass" type="password" autoComplete="current-password" required value={pw.current} onChange={e=>setPw({...pw,current:e.target.value})}/><label htmlFor="new-pass">New password</label><input id="new-pass" type="password" minLength={6} maxLength={72} autoComplete="new-password" required value={pw.next} onChange={e=>setPw({...pw,next:e.target.value})}/><label htmlFor="confirm-pass">Confirm new password</label><input id="confirm-pass" type="password" required autoComplete="new-password" value={pw.confirm} onChange={e=>setPw({...pw,confirm:e.target.value})}/><button className="block" disabled={busy}>Change password</button></form></section></div></>
}
