import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api } from '../../api'
import type { AdminUser } from '../../types'
import { Alert, Empty, Icon, Modal, PageTitle, typeLabel } from '../../ui'
export default function Users(){
 const [users,setUsers]=useState<AdminUser[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false)
 const [form,setForm]=useState({username:'',password:'',role:'debit_user',recovery:''});const navigate=useNavigate()
 useEffect(()=>{api.get<AdminUser[]>('/users').then(setUsers).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api.post<{user_id:string}>('/users',{username:form.username.trim(),password:form.password,role:form.role,recovery_number:form.recovery||null});navigate(`/users/${r.user_id}`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const shown=users.filter(u=>u.user_name.toLowerCase().includes(search.toLowerCase()))
 return <><PageTitle title="People" subtitle="Set up your team, their accounts, and where they can make entries." action={<button onClick={()=>{setCreating(true);setError('')}}><Icon name="plus" size={18}/>New person</button>}/>{!creating&&<Alert>{error}</Alert>}<section className="ledger"><div className="section-title"><h2>Your team <span className="count">{users.length}</span></h2><div className="search-field"><Icon name="search" size={18}/><input aria-label="Search people" placeholder="Find a person…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div>{loading?<div className="spin"/>:!shown.length?<Empty title="No people found">Try another name.</Empty>:<div className="table-scroll"><table className="data"><thead><tr><th>Person</th><th>Access type</th><th>Recovery number</th><th>Status</th><th/></tr></thead><tbody>{shown.map(u=><tr key={u.user_id}><td><div className="person-cell"><span className="avatar">{u.user_name[0].toUpperCase()}</span><Link to={`/users/${u.user_id}`}><strong>{u.user_name}</strong></Link></div></td><td>{typeLabel(u.user_role_name)}</td><td>{u.recovery_number||'Not set'}</td><td><span className={`tag ${u.is_active?'green':'muted'}`}>{u.is_active?'Active':'Inactive'}</span></td><td><Link className="subtle" to={`/users/${u.user_id}`}>Manage <Icon name="arrow" size={16}/></Link></td></tr>)}</tbody></table></div>}</section>{creating&&<Modal title="Welcome someone new" onClose={()=>{if(!busy)setCreating(false)}}><p>Create their account, then assign their heads.</p><Alert>{error}</Alert><form onSubmit={create}><label htmlFor="new-user">Username</label><input id="new-user" required minLength={3} maxLength={48} pattern="[A-Za-z0-9_.-]+" autoCapitalize="none" autoComplete="off" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><label htmlFor="new-password">Initial password</label><input id="new-password" type="password" required minLength={6} maxLength={72} autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><label htmlFor="new-role">Account type</label><select id="new-role" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="debit_user">Debit user · money out</option><option value="credit_user">Credit user · money in</option><option value="admin">Administrator · full access</option></select><label htmlFor="new-phone">Recovery phone (optional)</label><input id="new-phone" type="tel" maxLength={24} placeholder="+92 370 9676552" value={form.recovery} onChange={e=>setForm({...form,recovery:e.target.value})}/><button className="block" disabled={busy}>{busy?'Creating…':'Create & assign heads'}</button></form></Modal>}</>
}
